version: '3'
services:
    apache:
        build: .docker/apache
        container_name: sf4_apache
        ports:
          - 8000:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled:delegated
          - .:/home/wwwroot:delegated
        depends_on:
          - php

    postgres:
        container_name: sf4_postgres
        image: postgres:12-alpine
        environment:
            - POSTGRES_DB=sf4
            - POSTGRES_PASSWORD=sf4
            - POSTGRES_USER=sf4
        volumes:
            - .docker/data/db:/var/lib/postgresql/data:rw
        ports:
            - "15432:5432"

    php:
        build: .docker/php
        container_name: sf4_php
        ports:
          - 8080:8080
        volumes:
          - .:/home/wwwroot:delegated
        environment:
          - maildev_host=sf4_maildev
        depends_on:
          - maildev
          - postgres

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: sf4_phpmyadmin
        environment:
          PMA_HOST: postgres
          PMA_PORT: 5432
        ports:
            - 8001:80
        links:
            - postgres

    maildev:
        image: djfarrelly/maildev
        container_name: sf4_maildev
        ports:
          - 8002:80